### ISSUE TITLE
Simplify installation

### ISSUE THREAD

**Issue by ad-si** [purescript/npm-installer#10]
I tried to install PureScript in a Docker container with a [GraalVM](https://www.graalvm.org) backend. But because of some hacky postinstall steps it fails. Check out https://github.com/graalvm/graaljs/issues/157#issuecomment-492129793 for details.

Can we simplify this?

**Comment by hdgarrood** [comment]
@ad-si oh yeah of course, I forgot that was something you could do, thanks!
