### ISSUE TITLE
`npm install purescript` stuck

### ISSUE THREAD

**Issue by develop7** [purescript/npm-installer#12]
Repro:

Run `npm i -g purescript`

Expected: successful installation
Instead: installer gets stuck forever on a `⠹ Check if a prebuilt 0.13.2 binary is provided for Linux` step

![image](https://user-images.githubusercontent.com/89889/60756656-cfeb5600-a008-11e9-9773-203ee6e6a3fd.png)

**Comment by hdgarrood** [comment]
Can you provide your node and npm version please?

**Comment by develop7** [comment]
develop7@t-rex ~>  node --version
v11.15.0
develop7@t-rex ~>  npm --version
6.10.0

**Comment by skress** [comment]
Same problem here, Ubuntu 18.04, node 12.6.0, npm 6.9.0.

Installing version 0.13.0 works but installing 0.13.2 is stuck in the „Check if prebuilt ...“ step.

**Comment by doolse** [comment]
This appears to be a bug in npm package [load-from-cwd-or-npm](https://github.com/shinnn/load-from-cwd-or-npm) v3.0.2, as it doesn't seem to resolve "request" anymore. You can work-around this by pinning it to 3.0.1 in your package.json:

```json
"dependencies": {
    "purescript": "0.13.2",
    "load-from-cwd-or-npm": "3.0.1"
}
```

**Comment by hdgarrood** [comment]
Oops, accidentally closed via a commit keyword.

**Comment by hdgarrood** [comment]
I've published a new release which vendors `dl-tar` in order to require `request` in the standard way instead of using `load-from-cwd-or-npm`. It seems to fix the issue for me. Can anyone else check please?

**Comment by hdgarrood** [comment]
(Thanks @doolse for helping investigate!)

**Comment by skress** [comment]
Yes, it works again. Thanks for the fix!

**Comment by hdgarrood** [comment]
Great. Please open new issues if anything else arises.

**Comment by hdgarrood** [comment]
It turns out that this issue was deliberate sabotage. See https://harry.garrood.me/blog/malicious-code-in-purescript-npm-installer/

Thanks again to @doolse, whose investigation greatly helped in tracking this down.
