### ISSUE TITLE
Readme: dead link

### ISSUE THREAD

**Issue by andys8** [purescript/npm-installer#17]
Readme links to https://github.com/purescript-contrib/node-purescript. The link results `404`. There probably exists a new name for `node-purescript`

![Screenshot_20190728-223807](https://user-images.githubusercontent.com/13085980/62012593-8a91f280-b188-11e9-9a84-b840e4e4fc15.png)

**Comment by hdgarrood** [comment]
The sources for the `purescript` npm package are stored in https://github.com/purescript/purescript, so this link could point there, or it could just point straight to https://npmjs.com/package/purescript
