### ISSUE TITLE
NPM Installation Issue

### ISSUE THREAD

**Issue by jaredforth** [purescript/npm-installer#31]
I am following the [instructions](https://github.com/purescript/documentation/blob/master/guides/Getting-Started.md) for installing PureScript via the NPM installer. I ran `sudo npm install -g purescript`, which gave the following output: 

```
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/usr/local/bin/purs -> /usr/local/lib/node_modules/purescript/purs.bin

> purescript@0.14.0 postinstall /usr/local/lib/node_modules/purescript
> install-purescript --purs-ver=0.14.0
```

However, when I run `purs` to check the installation, the following message is logged: 

```
purescript npm installer: installation failed; please try installing again
```

I am on a PC running Windows 10 with Ubuntu 20.04 LTS installed via WSL (Windows Subsystem for Linux). All of the commands listed above are on Bash in WSL.

**Comment by garyb** [comment]
I think you're not supposed to `sudo` when using `npm install -g`. If you were doing that to work around an `EACCES` error, then there's this in the npm docs: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by hdgarrood** [comment]
Apparently, as of npm v7, when npm is run as root, scripts are always run with the effective uid and gid of the working directory owner. https://docs.npmjs.com/cli/v7/using-npm/scripts#user

I think this might be related to the issue you're seeing. I think what might be happening is that `install-purescript` is encountering a permission error and exiting silently, in which case we probably ought to have it fail more loudly with a non-zero exit code.

**Comment by jaredforth** [comment]
If I try to run without `sudo` I get the following different set of errors: 

```
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /home/jared/.nvm/versions/node/v15.12.0/lib/node_modules/purescript
npm ERR! command failed
npm ERR! command sh -c install-purescript --purs-ver=0.14.0
npm ERR! [ SUCCESS ] Check if a prebuilt 0.14.0 binary is provided for linux (602ms)
npm ERR! [ SUCCESS ] Download the prebuilt PureScript binary (683ms)
npm ERR! [ FAILURE ] Verify the prebuilt binary works correctly
npm ERR! Error: Command failed: /home/jared/.nvm/versions/node/v15.12.0/lib/node_modules/purescript/purs.bin --version
npm ERR! /home/jared/.nvm/versions/node/v15.12.0/lib/node_modules/purescript/purs.bin: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
npm ERR!
npm ERR!     at ChildProcess.exithandler (node:child_process:326:12)
npm ERR!     at ChildProcess.emit (node:events:369:20)
npm ERR!     at maybeClose (node:internal/child_process:1067:16)
npm ERR!     at Socket.<anonymous> (node:internal/child_process:453:11)
npm ERR!     at Socket.emit (node:events:369:20)
npm ERR!     at Pipe.<anonymous> (node:net:665:12)
npm ERR!
npm ERR! ↓ Fallback: building from source
npm ERR!
npm ERR! [ FAILURE ] Check if 'stack' command is available
npm ERR! Error: Command failed with exit code 2 (ENOENT): stack --allow-different-user --numeric-version
npm ERR! spawn stack ENOENT
npm ERR!     at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
npm ERR!     at onErrorNT (node:internal/child_process:480:16)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:81:21)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jared/.npm/_logs/2021-03-23T15_41_43_134Z-debug.log
```

**Comment by garyb** [comment]
Ah! that's a much more common problem: https://github.com/purescript/purescript/blob/master/INSTALL.md#the-curses-library

**Comment by jaredforth** [comment]
Yep running `sudo apt install libncurses5` and reinstalling via NPM solved the issue. I appreciate your time!

**Comment by garyb** [comment]
Glad you got it working. 🙂 

This particular problem has tripped up many people, we've had some discussion about whether we should just drop the dependency to avoid it (at the expense of the repl experience), and I think a few other ideas to possibly work around it, but just haven't settled on an answer for it yet.

**Comment by jaredforth** [comment]
@garyb Yes, I can see how this would have been an issue for others as well. I don't know what the best solution for that would be, but I'll think about it and reach out if I have any ideas.

**Comment by JordanMartinez** [comment]
Would it be possible to prevent such issues in the future by adding some message in the script that says, "Hey, if this fails to install PureScript, you might need to install the `libncurses5`" or something like that?

**Comment by jaredforth** [comment]
> Would it be possible to prevent such issues in the future by adding some message in the script that says, "Hey, if this fails to install PureScript, you might need to install the `libncurses5`" or something like that?

That could be a good solution! If this project is looking for new contributors I would be up to tackle the implementation of that if people think it is an acceptable fix.

**Comment by hdgarrood** [comment]
I'd prefer to just drop the ncurses dependency. It's a 4 line change in `stack.yaml` in the compiler, we just need to do the same as what we did here: https://github.com/purescript/spago/pull/684/files

**Comment by JoelLefkowitz** [comment]
If anyone arrived here having trouble installing PureScript on TravisCI I found the following worked.

```
sudo apt-get install libncurses5 libncurses5-dev
curl -L https://github.com/purescript/purescript/releases/download/v0.14.0/linux64.tar.gz --output linux64.tar.gz
tar -xzf linux64.tar.gz purescript/purs --strip-components=1
sudo mv purs /usr/local/bin/purs
```

Installing with npm after having installed libncurses5 did not resolve the issue and still resulted in:
```
npm ERR! [ FAILURE ] Check if 'stack' command is available
```
as @jaredforth had above.

Installing the PureScript version 0.14.1 binary resulted in:
```
purs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by purs)
```
